version: '3.7'

services:

  client:
    container_name: Client
    build: ./client
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true

  server:
    container_name: server
    build: ./server
      context: .
      dockerfile: Dockerfile